// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert/Alert.vue')['default']
    'Alert.story': typeof import('./components/Alert/Alert.story.vue')['default']
    AppContainer: typeof import('./components/AppContainer/AppContainer.vue')['default']
    Button: typeof import('./components/Button/Button.vue')['default']
    'Button.story': typeof import('./components/Button/Button.story.vue')['default']
    Card: typeof import('./components/Card/Card.vue')['default']
    'Card.story': typeof import('./components/Card/Card.story.vue')['default']
    FormItem: typeof import('./components/FormItem/FormItem.vue')['default']
    Input: typeof import('./components/Input/Input.vue')['default']
    Login: typeof import('./components/Login/Login.vue')['default']
    Navigation: typeof import('./components/Navigation/Navigation.vue')['default']
    PageNotifications: typeof import('./components/PageNotifications/PageNotifications.vue')['default']
    Pagination: typeof import('./components/Pagination/Pagination.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/Spinner/Spinner.vue')['default']
    SVG: typeof import('./components/SVG/SVG.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
